### ISSUE TITLE
Error Pre-Training Predictor: "model -> encoder -> encode_source   extra fields not permitted (type=value_error.extra)"

### ISSUE THREAD

**Issue by Qbop981001** [Unbabel/OpenKiwi#104]
When I use the predictor.yaml file in config/ to pretrain the predictor model, I got this error. The original message is:

> Traceback (most recent call last):
>   File "/root/anaconda3/envs/kiwi37/bin/kiwi", line 5, in <module>
>     main()
>   File "/root/qbp/qe/OpenKiwi-master/kiwi/__main__.py", line 21, in main
>     return kiwi.cli.cli()
>   File "/root/qbp/qe/OpenKiwi-master/kiwi/cli.py", line 84, in cli
>     train.train_from_configuration(config_dict)
>   File "/root/qbp/qe/OpenKiwi-master/kiwi/lib/train.py", line 249, in train_from_configuration
>     train_info = run(config)
>   File "/root/qbp/qe/OpenKiwi-master/kiwi/lib/train.py", line 341, in run
>     system = system_type.from_config(config.system, data_config=config.data)
>   File "/root/qbp/qe/OpenKiwi-master/kiwi/systems/qe_system.py", line 486, in from_config
>     config = system_cls.Config(**config.dict())
>   File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
> pydantic.error_wrappers.ValidationError: 1 validation error for Config
> model -> encoder -> encode_source
>   extra fields not permitted (type=value_error.extra)

As the message shows, I assume it is the error of model -> encoder ->encode_source, but in fact I did not revise the original example predictor.yaml file in this project. In the original file, the value of encode_source is set to "false". I tried to override it to "true", and I get the same error.
 How can I find the file demonstrating that how the values in .yaml file should be set ?

**Comment by captainvera** [comment]
hey @Qbop981001!

Sorry it took me a while to get a look at this. you are absolutely correct, it is indeed a bug in our example files.

The predictor encoder by default always encodes source, as such, that flag does not make sense and is probably a leftover from another config. 

The correct way to fix this is to simply remove the flag from the yaml :) 

Let me know if you have any other questions!
