### ISSUE TITLE
Unable to start openkiwi

### ISSUE THREAD

**Issue by knikolaou48** [Unbabel/OpenKiwi#79]
I am unable to run to start openkiwi it seems that I have properly installed everything needed. 

When I try to load the example typing kiwi --example I get the following message

(base) C:\Users\Administrator>kiwi --example
Traceback (most recent call last):
  File "c:\users\administrator\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\anaconda3\Scripts\kiwi.exe\__main__.py", line 7, in <module>
  File "c:\users\administrator\anaconda3\lib\site-packages\kiwi\__main__.py", line 21, in main
    return kiwi.cli.cli()
  File "c:\users\administrator\anaconda3\lib\site-packages\kiwi\cli.py", line 105, in cli
    config_dict = arguments_to_configuration(arguments)
  File "c:\users\administrator\anaconda3\lib\site-packages\kiwi\cli.py", line 68, in arguments_to_configuration
    config_file = Path(arguments['CONFIG_FILE'])
  File "c:\users\administrator\anaconda3\lib\pathlib.py", line 1038, in __new__
    self = cls._from_parts(args, init=False)
  File "c:\users\administrator\anaconda3\lib\pathlib.py", line 679, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "c:\users\administrator\anaconda3\lib\pathlib.py", line 663, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

 - OS: Windows 10 64 bit
 - OpenKiwi version 2.0.0
 - Python version 3.8.3
 - Anaconda 
 - Pytorch Build 1.7.0

**Comment by captainvera** [comment]
Hi @knikolaou48,

I am assuming you installed from master?

I was able to reproduce your bug on the latest master. It was introduced in #76.
Kiwi should be working fully except for the --example command. You can test this by running `kiwi train -h`.

I will make a PR to fix this, thanks for bringing it to our attention!
